[package]
name = "rusty-piano"
version = "0.1.0"
edition = "2024"

[dependencies]
blowfish = "0.9.1"
byteorder = "1.5.0"
cipher = "0.4.4"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
rodio = { version = "0.21.1", default-features = false, features = ["playback", "mp3"]}
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.141"
